name: Build and publish to gh-pages
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile main-german.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: lfgw.tex
          args:
      - name: Gather build artifacts
        run: mkdir build && cp -lfgw.pdf build/
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@master
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
