name: Build and publish to gh-pages
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
        with:
          depth: 1
      - name: Compile lfgw.tex with lualatex
        uses: dante-ev/latex-action@master
        with:
          root_file: lfgw.tex
          compiler: lualatex
          args: -interaction=nonstopmode
      - name: Compile lfgw.tex with biber
        uses: dante-ev/latex-action@master
        with:
          root_file: lfgw
          compiler: biber
          args:
      - name: Compile lfgw.tex with lualatex
        uses: dante-ev/latex-action@master
        with:
          root_file: lfgw.tex
          compiler: lualatex
          args: -interaction=nonstopmode
      - name: Compile lfgw.tex with lualatex
        uses: dante-ev/latex-action@master
        with:
          root_file: lfgw.tex
          compiler: lualatex
          args: -interaction=nonstopmode
      - name: Gather build artifacts
        run: mkdir build && cp lfgw.pdf build/
      - name: Publish to GitHub pages (gh-pages)
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
